"""
https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:
                    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

sum = 0
def Fibonacci(n1, n2):
    global sum
    output = n1 + n2
    if output % 2 == 0:
        sum += output
    if output >= 4_000_000:
        print(sum)
        quit()
    Fibonacci(n2, output)

print(Fibonacci(0, 1))
